/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2022-11-13 15:13:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1666953040000L));
    _jspx_dependants.put("jar:file:/E:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sportingcomplex/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1664986175786L));
    _jspx_dependants.put("jar:file:/E:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sportingcomplex/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1665049534266L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Trang chu</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Slider -->\r\n");
      out.write("\t<div class=\"slider\">\r\n");
      out.write("\t\t<div id=\"carouselExampleIndicators\" class=\"carousel slide\"\r\n");
      out.write("\t\t\tdata-bs-ride=\"true\">\r\n");
      out.write("\t\t\t<div class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("\t\t\t\t\tdata-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Slide 1\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("\t\t\t\t\tdata-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("\t\t\t\t\tdata-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("\t\t\t\t\tdata-bs-slide-to=\"3\" aria-label=\"Slide 4\"></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t\t<img src=\"template/web/asset/img/slider1.png\" class=\"d-block w-100\"\r\n");
      out.write("\t\t\t\t\t\talt=\"...\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"template/web/asset/img/Slider2.jpg\" class=\"d-block w-100\"\r\n");
      out.write("\t\t\t\t\t\talt=\"...\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"template/web/asset/img/Slider3.jpg\" class=\"d-block w-100\"\r\n");
      out.write("\t\t\t\t\t\talt=\"...\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"template/web/asset/img/slider4.jpg\" class=\"d-block w-100\"\r\n");
      out.write("\t\t\t\t\t\talt=\"...\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"hider\"></div>\r\n");
      out.write("\t\t\t<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("\t\t\t\t<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("\t\t\t\t<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"seacher\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"search\"\r\n");
      out.write("\t\t\t\tplaceholder=\" Tìm kiếm sân và thông tin khóa học\">\r\n");
      out.write("\t\t\t<button type=\"button\">TÌM KIẾM</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"slogan\">THỂ THAO KẾT NỐI MỌI NGƯỜI</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Slider -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- News -->\r\n");
      out.write("\t<div class=\"news\">\r\n");
      out.write("\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t<div class=\"paper\">\r\n");
      out.write("\t\t\t\t<img src=\"https://i.ytimg.com/vi/MkFYEnDrSYg/maxresdefault.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t<h6>2 tiếng trước</h6>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span>THÔNG BÁO : </span> Giải đấu cầu lông nghiệp dư mở rộng sẽ\r\n");
      out.write("\t\t\t\t\t\tdiễn ra từ ngày 22/9/2022 đến ngày 1/10/2022\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"paper\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"https://th.bing.com/th/id/R.35f14613a126b51b44c250f0e0e3ae50?rik=PMNSYbgCEbbZAA&riu=http%3a%2f%2fmeteccons.vn%2fimg_data%2fimages%2fricons-3125266855342.jpg&ehk=5QbkW9vJJzW1RltbxzF0SwmKmIiCKexcu7sZBP2TgNY%3d&risl=&pid=ImgRaw&r=0\"\r\n");
      out.write("\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t<h6>1 ngày trước</h6>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span>VINH DANH : </span> DreamFC - Nhà vô địch giải bóng đá phủi\r\n");
      out.write("\t\t\t\t\t\tSPORTING CUP\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"paper\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"https://images.prismic.io/fft-rg-commun-news/9d9929b8-612c-4368-b404-899aaf2bc463_Roger+Federer+-+Roland-Garros+2009+-+Eric+Della+Torre+FFT.jpg?auto=compress,format\"\r\n");
      out.write("\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t<h6>30 phút trước</h6>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span>SỰ KIỆN : </span> Gặp mặt huyền thoại làng banh nỉ Roger\r\n");
      out.write("\t\t\t\t\t\tFederer\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End News -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<div class=\"info\">\r\n");
      out.write("\t\t<div class=\"con1\">\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>HỖ TRỢ</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> Hướng dẫn đặt sân online </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> Hướng dẫn đăng ký tài khoản </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> Hướng dẫn đăng ký khóa học </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>CHÍNH SÁCH</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> Chính sách về tiền cọc </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> Chính sách về đồ thuê </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> Chính sách về cơ sở vật chất </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>KẾT NỐI</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"https://www.facebook.com/canhhung.nguyen.33\">\r\n");
      out.write("\t\t\t\t\t\t\tFacebook </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> Instagram </a></li>\r\n");
      out.write("\t\t\t\t\t<li>Hotline: 0999.999.999</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"con2\">\r\n");
      out.write("\t\t\t<div class=\"about\">\r\n");
      out.write("\t\t\t\t<div class=\"in4\">KHU LIÊN HỢP THẾ THAO CHẤT LƯỢNG CAO SPORTING\r\n");
      out.write("\t\t\t\t\tCOMPLEX</div>\r\n");
      out.write("\t\t\t\t<div class=\"in4\">\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://www.google.com/maps/place/Ho%C3%A0ng+C%C6%B0%C6%A1ng,+Thanh+Ba,+Ph%C3%BA+Th%E1%BB%8D,+Vi%E1%BB%87t+Nam/@21.4441847,105.0952567,14z/data=!3m1!4b1!4m9!1m2!2m1!1za2h1IDIgaG_DoG5nIGPGsMahbmcgdGhhbmggYmEgcGjDuiB0aOG7jQ!3m5!1s0x31349bfe71c7cd1b:0x280f25c5a56e2886!8m2!3d21.4492519!4d105.1288193!15sCihraHUgMiBob8OgbmcgY8awxqFuZyB0aGFuaCBiYSBwaMO6IHRo4buNkgEUYWRtaW5pc3RyYXRpdmVfYXJlYTPgAQA\">Địa\r\n");
      out.write("\t\t\t\t\t\tchỉ : Khu 2, Hoàng Cương, Thanh Ba, Phú Thọ</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"in4\">Fax: 123.123.441.311</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\turl=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t    const btnLogin = document.querySelector(\".js-log-in\"); // lất ra class của nút đăng nhập trên header để mở modal\r\n");
      out.write("\t    const modalBtn = document.querySelector(\".js-modal__1\"); // lấy ra class để bật modal\r\n");
      out.write("\t\r\n");
      out.write("\t    const registerForm = document.querySelector(\".js-Form-Register\"); // lấy ra class để mở và đóng form đăng kí\r\n");
      out.write("\t    const btnSwitchFormToFormRegister = document.querySelector(\".js-switch-form-Register\"); // lấy class để chuyển từ form đăng nhập sang form đăng kí\r\n");
      out.write("\t\r\n");
      out.write("\t    const loginForm = document.querySelector(\".js-Form-logIn\"); // lấy ra class để đóng mở form đăng nhập\r\n");
      out.write("\t    const btnSwitchFormToFormLogins = document.querySelectorAll(\".js-switch-form-LogIn\"); // lấy ra class của nút chuyển từ form đăng kí về lại form đăng nhập\r\n");
      out.write("\t\r\n");
      out.write("\t    const btnForgotPassword = document.querySelector(\".js-btn__forgot\"); // lấy ra class nút quên mật khẩu để mở form quên mật khẩu\r\n");
      out.write("\t    const forgotPasswordForm = document.querySelector(\".js-form__forgot\"); // lấy ra class của form quên mật khẩu để đóng mở form\r\n");
      out.write("\t\r\n");
      out.write("\t    const confirmForm = document.querySelector(\".js-form__message\"); // lấy class của form xác nhận để đóng mở form\r\n");
      out.write("\t    const btnSendConfirm = document.querySelector(\".js-btn__send-massage\"); // lấy class nút xác nhận để chuyển sang form nhập mã xác nhận và đổi mật khẩu\r\n");
      out.write("\t\r\n");
      out.write("\t    const btnBackFormForgotPassword = document.querySelector(\".js-back__forgotPassword\"); // lấy class của nút trở lại trong form confirm để comeback form forgot password\r\n");
      out.write("\t\r\n");
      out.write("\t    const closeAll = document.querySelector(\".js-modal__overlay\"); // lấy ra class của lớp phủ để đóng tất cả form lại\r\n");
      out.write("\t    const closeAllByButtonOfLofinForm = document.querySelector(\".js-remove\");\r\n");
      out.write("\t    // mở modal và form đăng nhập\r\n");
      out.write("\t    function showmodal() {\r\n");
      out.write("\t    \tmodalBtn.classList.add(\"open\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t    btnLogin.addEventListener(\"click\", showmodal);\r\n");
      out.write("\t\r\n");
      out.write("\t    // Chuyển tư form đăng nhập sang đăng kí\r\n");
      out.write("\t    function switchFromLoginToFormRegister() {\r\n");
      out.write("\t    \t// loại bỏ class remove của form đăng kí để hiện form\r\n");
      out.write("\t    \tregisterForm.classList.remove(\"remove\");\r\n");
      out.write("\t    \t// thêm class remove vào form đăng nhập để ẩn form đăng nhập\r\n");
      out.write("\t    \tloginForm.classList.add(\"remove\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t    btnSwitchFormToFormRegister.addEventListener(\"click\", switchFromLoginToFormRegister);\r\n");
      out.write("\t\r\n");
      out.write("\t    // chuyển từ form đăng kí sang form đăng nhập\r\n");
      out.write("\t    function switchFromRegisterToFormLogin() {\r\n");
      out.write("\t    \t// thêm class remove vào form đăng kí để ẩn\r\n");
      out.write("\t    \tregisterForm.classList.add(\"remove\");\r\n");
      out.write("\t    \t// loại bỏ class remove của form đăng nhập để hiện form đăng nhập\r\n");
      out.write("\t    \tloginForm.classList.remove(\"remove\");\r\n");
      out.write("\t    \t// thêm class remove vào form quên đăng nhập để ẩn form\r\n");
      out.write("\t    \tforgotPasswordForm.classList.add(\"remove\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t    for (const btnSwitchFormToFormLogin of btnSwitchFormToFormLogins) {\r\n");
      out.write("\t    \tbtnSwitchFormToFormLogin.addEventListener(\"click\", switchFromRegisterToFormLogin);\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    // mở form quên mật khẩu\r\n");
      out.write("\t    function showFormForgot() {\r\n");
      out.write("\t    \t// thêm class remove vào form đăng nhập để ẩn form đăng nhập\r\n");
      out.write("\t    \tloginForm.classList.add(\"remove\");\r\n");
      out.write("\t    \t// loại bỏ class remove của form quên đăng nhập để hiện form\r\n");
      out.write("\t    \tforgotPasswordForm.classList.remove(\"remove\");\r\n");
      out.write("\t    \t// thêm class remove vào form confirm để ẩn form\r\n");
      out.write("\t    \tconfirmForm.classList.add(\"remove\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t    btnForgotPassword.addEventListener(\"click\", showFormForgot);\r\n");
      out.write("\t\r\n");
      out.write("\t    // mở form xác nhận mã và đổi mật khẩu\r\n");
      out.write("\t    function showFormConfirm() {\r\n");
      out.write("\t    \t// loại bỏ class remove của form confirm để mở form\r\n");
      out.write("\t    \tconfirmForm.classList.remove(\"remove\");\r\n");
      out.write("\t    \t// thêm class remove vào form quên đăng nhập để ẩn form\r\n");
      out.write("\t    \tforgotPasswordForm.classList.add(\"remove\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t    btnSendConfirm.addEventListener(\"click\", showFormConfirm);\r\n");
      out.write("\t\r\n");
      out.write("\t    // mở lại form forgot password và close form confirm\r\n");
      out.write("\t    btnBackFormForgotPassword.addEventListener(\"click\", showFormForgot);\r\n");
      out.write("\t\r\n");
      out.write("\t    // đóng các form khi click ra ngoài của form bất kì\r\n");
      out.write("\t    function close() {\r\n");
      out.write("\t    \t// ẩn form đăng kí\r\n");
      out.write("\t    \tregisterForm.classList.add(\"remove\");\r\n");
      out.write("\t    \t// ẩn form xác nhận\r\n");
      out.write("\t    \tconfirmForm.classList.add(\"remove\");\r\n");
      out.write("\t    \t// ẩn form quên mật khẩu\r\n");
      out.write("\t    \tforgotPasswordForm.classList.add(\"remove\");\r\n");
      out.write("\t    \t// hiện form đăng nhập\r\n");
      out.write("\t    \tloginForm.classList.remove(\"remove\");\r\n");
      out.write("\t    \t// tắt modal\r\n");
      out.write("\t    \tmodalBtn.classList.remove(\"open\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t    closeAll.addEventListener(\"click\", close);\r\n");
      out.write("\t    closeAllByButtonOfLofinForm.addEventListener(\"click\", close);\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/web/home.jsp(155,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("template/web/asset/JS/main.js");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
